import Link from "next/link"
import Image from "next/image"
import Head from "next/head"
import home from "../public/images/home.jpg"
import Property from "../components/Property"
import Clients from "../layouts/Clients"
import { baseUrl, fetchApi } from "../utils/fetchApi"
import Services from "../layouts/Services"
import Contact from "../layouts/Contact"
import Footer from "../components/Footer"


export default function Home({propertiesForSale, propertiesForRent}) {
  console.log(propertiesForSale, propertiesForRent);
  return (
    <div>
      <Head>
        <title>Urban Real Estate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex home pt-16">
        <div className="w-full h-full">
          <Image src={home} alt="/" width={800} height={1500}/>
        </div>
          
          <div className="p-20 home-text">
            <h1 className="text-3xl pb-7">
          A demo with MLS listings powered by mlsimport.com
          </h1>
          <p className="pb-8">Integrate MLS Listings seamlessly with your existing WpResidence website. Import and sync properties through MLSImport.com solution</p>
          <input className="placeholder:italic placeholder:text-slate-400 block bg-white w-3/6 rounded-md py-2 pl-5 pr-3 shadow-sm focus:outline-none focus:border-sky-500 focus:ring-sky-500 focus:ring-1 sm:text-sm home-input" placeholder="Search Location..." type="text" name="search"/>
          </div>
          
      </div>

      <div className='w-full h-full py-16 px-10'>
            <div className='flex flex-col gap-10'>
              <div>
                <h1 className='text-[#0eafef] text-3xl tracking-widest font-bold py-2 pl-5'>Properties For Rent</h1>
                <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8'>
                  {propertiesForRent?.map((property) => <Property property= {property} key={property.id}/>)}
                </div>
              </div>

              <div>
                <h1 className='text-[#0eafef] text-3xl tracking-widest font-bold py-2 pl-5'>Properties For Sale</h1>
                <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8'>
                  {propertiesForSale?.map((property) => <Property property= {property} key={property.id}/>)}
                </div>
              </div>
            </div>
          </div> 
          <Clients/>
          <Services />
          <Contact />
          <div>
          <h1 className='px-10 text-2xl tracking-widest font-normal text-[#00afef] text-left md:text-center'>Watch this video to know us better</h1>
          <div className="flex justify-center items-center py-8">
          <iframe width="560" height="315" src="https://www.youtube.com/embed/3nTWlTXsAJw" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </div>
          </div>
          <Footer />
    </div>
  )

}

export async function getStaticProps() {
  const propertyForSale = await fetchApi(`${baseUrl}/properties/list?locationExternalIDs=5002&purpose=for-sale&hitsPerPage=6`)
  const propertyForRent = await fetchApi(`${baseUrl}/properties/list?locationExternalIDs=5002&purpose=for-rent&hitsPerPage=6`)

  return {
    props: {
      propertiesForSale: propertyForSale?.hits,
      propertiesForRent: propertyForRent?.hits,
    },
  };
}
